res_txt = "data/res.txt"
res_html = "templates/res.html"
scores_html = "templates/scores.html"
img_path = "static/res.png"
shp = "data/better_sil2.shp"
neigh_data = "data/neighbours.data"
currneigh_data = "data/current_neighbours.data"
conq_data = "data/conquered.data"